Select PERIODO,
       FUENTE,
	    --CODIGOCOMERCIO,
	    --TERMINAL,
       Sum( [VolTOT]) As brpv_vol_tot,
       Sum( [TxsTOT]) As brpv_txs_tot,
       Sum( [CTTOT]) As brpv_ct_tot,
       Sum( [CVTOT]) As brpv_cv_tot,
       Sum( [Vol_Nacional]) As brpv_vol_nacional,
       Sum( [Txn_Nacional]) As brpv_txn_nacional,
       Sum( [Vol_Internacional]) As brpv_vol_internacional,
       Sum( [Txn_Internacional]) As brpv_txn_internacional,
       Sum( [VolCEN]) As brpv_vol_cen,
       Sum( [VolCEI]) As brpv_vol_cei,
       Sum( [VolDN]) As brpv_vol_dn,
       Sum( [VolDI]) As brpv_vol_di,
       Sum( [VolCMN]) As brpv_vol_cmn,
       Sum( [VolCMI]) As brpv_vol_cmi,
       Sum( [TxsCEN]) As brpv_txs_cen,
       Sum( [TxsCEI]) As brpv_txs_cei,
       Sum( [TxsDN]) As brpv_txs_dn,
       Sum( [TxsDI]) As brpv_txs_di,
       Sum( [TxsCMN]) As brpv_txs_cmn,
       Sum( [TxsCMI]) As brpv_txs_cmi,
       Sum( [CTCEN]) As brpv_ct_cen,
       Sum( [CTCEI]) As brpv_ct_cei,
       Sum( [CTDN]) As brpv_ct_dn,
       Sum( [CTDI]) As brpv_ct_di,
       Sum( [CTCMN]) As brpv_ct_cmn,
       Sum( [CTCMI]) As brpv_ct_cmi,
       Sum( [CVCEN]) As brpv_cv_cen,
       Sum( [CVCEI]) As brpv_cv_cei,
       Sum( [CVDN]) As brpv_cv_dn,
       Sum( [CVDI]) As brpv_cv_di,
       Sum( [CVCMN]) As brpv_cv_cmn,
       Sum( [CVCMI]) As brpv_cv_cmi,
       Sum( [Vol Hib]) As brpv_vol_hib,
       Sum( [Fee txs Fee])As brpv_fee_txs_fee,
       Sum( [ENF]) As brpv_enf,
       Sum( [Tkt]) As brpv_tkt,
       Sum( [Com Total]) As brpv_com_total,
       Sum( [Com Vsnt1L]) As brpv_com_vsnt1l,
       Sum( [T. Interc]) As brpv_t_interc,
       Sum( [Com Emi Tot]) As brpv_com_emi_tot,
       Sum( [Com Emi Loc]) As brpv_com_emi_loc,
       Sum( [Com Emi For]) As brpv_com_emi_for,
       Sum( [DCC Costo]) As brpv_dcc_costo,
       Sum( [DCC Ingreso]) As brpv_dcc_ingreso,
       Sum( [L0800 Costo]) As brpv_l0800_costo,
       Sum( [L0800 Ingreso]) As brpv_l0800_ingreso,
       Sum( [EECC Ingreso]) As brpv_eecc_ingreso,
       Sum( [EECC Costo]) As brpv_eecc_costo,
       Sum( [Alquiler Ingreso]) As brpv_alquiler_ingreso,
       Sum( [PreAutorizacion Ingreso]) As brpv_preautorizacion_ingreso,
       Sum( [Robos Ingreso]) As brpv_robos_ingreso,
       Sum( [Visitas Costo]) As brpv_visitas_costo,
       Sum( [Afiliacion Costo]) As brpv_afiliacion_costo,
       Sum( [Depreciacion Costo]) As brpv_depreciacion_costo,
       Sum( [Chips Costo]) As brpv_chips_costo,
       Sum( [Personal Costo]) As brpv_personal_costo,
       Sum( [Publicidad Costo]) As brpv_publicidad_costo,
       Sum( [Testing Factory Costo]) As brpv_testing_factory_costo,
       Sum( [Desarrollo Costo]) As brpv_desarrollo_costo,
       Sum( [Reparacion Accesorios]) As brpv_reparacion_accesorios,
       Sum( [Recupero Costo]) As brpv_recupero_costo,
       Sum( [Instalacion Costo]) As brpv_instalacion_costo,
       Sum( [Telecarga Costo]) As brpv_telecarga_costo,
       Sum( [Suministro Costo]) As brpv_suministro_costo,
       Sum( [Com Vsnt]) As brpv_com_vsnt,
       Sum( [C Var Txs Total]) As brpv_c_var_txs_total,
       Sum( [Cost Infraestructura]) As brpv_cost_infraestructura,
       Sum( [Cost Licencia E-Core]) As brpv_cost_licencia_e_core,
       Sum( [Cost Monitoreo]) As brpv_cost_monitoreo,
       Sum( [Cost Soporte]) As brpv_cost_soporte,
       Sum( [Personal Adecco]) As brpv_personal_adecco,
       Sum( [Cost Autenticacion]) As brpv_cost_autenticacion,
       Sum( [Ingreso Poket]) As brpv_ingreso_poket,
       Sum( [Cost Poket]) As brpv_cost_poket,
       Sum( [Cost CyberSource]) As brpv_cost_cybersource,
       Sum( [Ing CyberSource]) As brpv_ing_cybersource,
       Sum( [Ing Renovacion]) As brpv_ing_renovacion,
       Sum( [Cost AgenteTercero]) As brpv_cost_agentetercero,
       Sum( [Inc AgenteTercero]) As brpv_inc_agentetercero,
       Sum( [Cost VerifiedbyVisa]) As brpv_cost_verifiedbyvisa,
       Sum( [Cost Geopagos]) As brpv_cost_geopagos,
       Sum( [Cost Tercerizado]) As brpv_cost_tercerizado,
       Sum( [Ing Afiliaciones]) As brpv_ing_afiliaciones,
       Sum( [Ingreso por mantenimiento]) As brpv_ingreso_por_mantenimiento,
       Sum( [Ingreso por renovacion]) As brpv_ingreso_por_renovacion,
       Sum( [Ingreso por transaccion]) As brpv_ingreso_por_transaccion,
       Sum( [Costo Envio Poket]) As brpv_costo_envio_poket,
       Sum( [Costo Alignet]) As brpv_costo_alignet,
       Sum( [Costo Amortizaciones]) As brpv_costo_amortizaciones,
       Sum( [Afiliacion REC]) As brpv_afiliacion_rec,
       Sum( [Mantenimiento REC]) As brpv_mantenimiento_rec,
       Sum( [OtrosRDP]) As brpv_otros_rdp,
       Sum( [Ferias y eventos]) As brpv_ferias_y_eventos,
       Sum( [Impr Laser]) As brpv_impr_laser,
       Sum( [InstaDiariaExpress]) As brpv_insta_diaria_express,
       Sum( [InstaEventosExpress]) As brpv_insta_eventos_express,
       Sum( [MPOS_RDP]) As brpv_mpos_rdp,
       Sum( [Cost Contometro]) As brpv_cost_contometro,
       Sum( [Cost Migraciones]) As brpv_cost_migraciones,
       Sum( [IngfeeMenbresia]) As brpv_ing_fee_membresia,
       Sum( [CostPlugIN]) As brpv_cost_plugin,
       Sum( [IngresoSetUP]) As brpv_ingreso_setup,
       Sum( [Replugin]) As brpv_replugin,
       Sum( [IngresoRefacturacionMKT]) As brpv_ingreso_refacturacion_mkt,
       Sum( [IngresoRefacturacionServicios]) As brpv_ingreso_refacturacion_servicios,
       Sum( [IngresoAporteVISAMKT]) As brpv_ingreso_aporte_visa_mkt,
       Sum( [GastoRefacturacionMKT]) As brpv_gasto_refacturacion_mkt,
       Sum( [GastoRefacturacionServicios]) As brpv_gasto_refacturacion_servicios,
       Sum( [GastoAporteVISAMKT]) As brpv_gasto_aporte_visa_mkt,
       Sum( [Afiliacion Generado Costo]) As brpv_afiliacion_generado_costo,
       Sum( [Afiliacion Habilitado Costo]) As brpv_afiliacion_habilitado_costo,
       Sum( [Afiliacion CPA CorporativoDCC]) As brpv_afiliacion_cpa_corporativo_dcc,
       Sum( [Afiliacion CPA VariableDCC]) As brpv_afiliacion_cpa_variable_dcc,
       Sum( [Afiliacion CPA DigitMonit]) As brpv_afiliacion_cpa_digit_monit,
       Sum( [Ingreso Trxs Vendomatica]) As brpv_ingreso_trxs_vendomatica,
       Sum( [Ingreso Gobierno]) As brpv_ingreso_gobierno,
       Sum( [Incobrable]) As brpv_incobrable,
       Sum( [FeeTransporte]) As brpv_fee_transporte,
       Sum( [GastoPostVenta]) As brpv_gasto_postventa,
       Sum( [TransaccionesData]) As brpv_transacciones_data,
       Sum( [POSCobrar]) As brpv_pos_cobrar,
       Sum( [Tarjetas]) As brpv_tarjetas,
       Sum( [IngresosTransaccionesData]) As brpv_ingresos_transacciones_data,
       Sum( [IngresosPOSActivo]) As brpv_ingresos_pos_activo,
       Sum( [IngresosTarjetas]) As brpv_ingresos_tarjetas,
       Sum( [IngresosSolucionesFraude]) As brpv_ingresos_soluciones_fraude,
       Sum( [IngresosSetUp]) As brpv_ingresos_setup,
       Sum( [IngresosMantenimiento]) As brpv_ingresos_mantenimiento,
       Sum( [OtrosIngresos]) As brpv_otros_ingresos,
       Sum( [OtrosGastosServicios]) As brpv_otros_gastos_servicios,
       Sum( [GastoProducto]) As brpv_gasto_producto,
       Sum( [GastoFlotas]) As brpv_gasto_flotas,
       Sum( [Niif_Afiliacion]) As brpv_niif_afiliacion,
       Sum( [Niif_Subsidio]) As brpv_niif_subsidio,
       Sum( [IngresosIzipay]) As brpv_ingresos_izipay,
       Sum( [GastosIzipay]) As brpv_gastos_izipay,
       Sum( [CostoProcesamiento]) As brpv_costo_procesamiento,
       Sum( [IngresosRecargasServicios]) As brpv_ingresos_recargas_servicios,
       Sum( [GastoRecargasServicios]) As brpv_gasto_recargas_servicios,
       Sum( [IngresosPrestamos]) As brpv_ingresos_prestamos,
       Sum( [IngresosPeajes]) As brpv_ingresos_peajes,
       Sum( [CostoCupo]) As brpv_costo_cupo,
       Sum( [GastoEventualRemplazo]) As brpv_gasto_eventual_remplazo,
       Sum( [Gasto_SIG]) As brpv_gasto_sig,
       Sum( [Gasto_CrossNiubiz]) As brpv_gasto_cross_niubiz,
       Sum( [personal_costo_procesamiento]) As brpv_personal_costo_procesamiento,
       Sum( [CostoVarTxsVisaDirect]) As brpv_costo_var_txs_visa_direct,
       Sum( [CostoVarTxsVisa]) As brpv_costo_var_txs_visa,
       Sum( [CostoVarTxsMC]) As brpv_costo_var_txs_mc,
       Sum( [GastoNBOProcesamiento]) As brpv_gasto_nbo_procesamiento,
       Sum( [GastoCanales]) As brpv_gasto_canales,
       Sum( [GastoComercio]) As brpv_gasto_comercio,
       Sum( [CostoAnalytics]) As brpv_costo_analytics,
       Sum( [CostoSAS]) As brpv_costo_sas,
       Sum( [GastoAmortizacionSAS]) As brpv_gasto_amortizacion_sas,
       Sum( [PeajesProcesam]) As brpv_peajes_procesam,
       Sum( [Gasto_CrossOnline]) As brpv_gasto_cross_online,
       Sum( [Gasto_CrossUnidad]) As brpv_gasto_cross_unidad,
       Sum( [ContraCargo]) As brpv_contra_cargo,
       Sum( [GastoAlquilerEquipo]) As brpv_gasto_alquiler_equipo,
       Sum( [GastoControversiasAsumidas]) As brpv_gasto_controversias_asumidas,
       Sum( [TRX_MC_FOR_1]) As brpv_trx_mc_for_1,
       Sum( [TRX_MC_FOR_1_5]) As brpv_trx_mc_for_1_5,
       Sum( [TRX_MC_FOR_5]) As brpv_trx_mc_for_5,
       Sum( [TRX_MC_NAC_1]) As brpv_trx_mc_nac_1,
       Sum( [TRX_MC_NAC_1_5]) As brpv_trx_mc_nac_1_5,
       Sum( [TRX_MC_NAC_10_25]) As brpv_trx_mc_nac_10_25,
       Sum( [TRX_MC_NAC_25]) As brpv_trx_mc_nac_25,
       Sum( [TRX_MC_NAC_5_10]) As brpv_trx_mc_nac_5_10,
       Sum( [TRX_VI_CRE_FOR_NP_0_5]) As brpv_trx_vi_cre_for_np_0_5,
       Sum( [TRX_VI_CRE_FOR_NP_100_250]) As brpv_trx_vi_cre_for_np_100_250,
       Sum( [TRX_VI_CRE_FOR_NP_15_50]) As brpv_trx_vi_cre_for_np_15_50,
       Sum( [TRX_VI_CRE_FOR_NP_250]) As brpv_trx_vi_cre_for_np_250,
       Sum( [TRX_VI_CRE_FOR_NP_5_15]) As brpv_trx_vi_cre_for_np_5_15,
       Sum( [TRX_VI_CRE_FOR_NP_50_100]) As brpv_trx_vi_cre_for_np_50_100,
       Sum( [TRX_VI_CRE_FOR_P_0_5]) As brpv_trx_vi_cre_for_p_0_5,
       Sum( [TRX_VI_CRE_FOR_P_100_250]) As brpv_trx_vi_cre_for_p_100_250,
       Sum( [TRX_VI_CRE_FOR_P_15_50]) As brpv_trx_vi_cre_for_p_15_50,
       Sum( [TRX_VI_CRE_FOR_P_250]) As brpv_trx_vi_cre_for_p_250,
       Sum( [TRX_VI_CRE_FOR_P_5_15]) As brpv_trx_vi_cre_for_p_5_15,
       Sum( [TRX_VI_CRE_FOR_P_50_100]) As brpv_trx_vi_cre_for_p_50_100,
       Sum( [TRX_VI_CRE_NAC_P_0_2]) As brpv_trx_vi_cre_nac_p_0_2,
       Sum( [TRX_VI_CRE_NAC_P_15_50]) As brpv_trx_vi_cre_nac_p_15_50,
       Sum( [TRX_VI_CRE_NAC_P_2_5]) As brpv_trx_vi_cre_nac_p_2_5,
       Sum( [TRX_VI_CRE_NAC_P_5_15]) As brpv_trx_vi_cre_nac_p_5_15,
       Sum( [TRX_VI_CRE_NAC_P_50]) As brpv_trx_vi_cre_nac_p_50,
       Sum( [TRX_VI_DEB_FOR_NP_0_5]) As brpv_trx_vi_deb_for_np_0_5,
       Sum( [TRX_VI_DEB_FOR_NP_100_250]) As brpv_trx_vi_deb_for_np_100_250,
       Sum( [TRX_VI_DEB_FOR_NP_15_50]) As brpv_trx_vi_deb_for_np_15_50,
       Sum( [TRX_VI_DEB_FOR_NP_250]) As brpv_trx_vi_deb_for_np_250,
       Sum( [TRX_VI_DEB_FOR_NP_5_15]) As brpv_trx_vi_deb_for_np_5_15,
       Sum( [TRX_VI_DEB_FOR_NP_50_100]) As brpv_trx_vi_deb_for_np_50_100,
       Sum( [TRX_VI_DEB_FOR_P_0_5]) As brpv_trx_vi_deb_for_p_0_5,
       Sum( [TRX_VI_DEB_FOR_P_100_250]) As brpv_trx_vi_deb_for_p_100_250,
       Sum( [TRX_VI_DEB_FOR_P_15_50]) As brpv_trx_vi_deb_for_p_15_50,
       Sum( [TRX_VI_DEB_FOR_P_250]) As brpv_trx_vi_deb_for_p_250,
       Sum( [TRX_VI_DEB_FOR_P_5_15]) As brpv_trx_vi_deb_for_p_5_15,
       Sum( [TRX_VI_DEB_FOR_P_50_100]) As brpv_trx_vi_deb_for_p_50_100,
       sum( [TRX_VI_DEB_NAC_P_0_2])  as brpv_trx_vi_deb_nac_p_0_2 ,
       sum( [TRX_VI_DEB_NAC_P_15_50])  as brpv_trx_vi_deb_nac_p_15_50 ,
       sum( [TRX_VI_DEB_NAC_P_2_5])  as brpv_trx_vi_deb_nac_p_2_5 ,
       sum( [TRX_VI_DEB_NAC_P_5_15])  as brpv_trx_vi_deb_nac_p_5_15 ,
       sum( [TRX_VI_DEB_NAC_P_50])  as brpv_trx_vi_deb_nac_p_50 ,
       Sum( [TRX_MC_FOR_5_Menos]) As brpv_trx_mc_for_5_menos,
       Sum( [TRX_MC_FOR_5_25]) As brpv_trx_mc_for_5_25,
       Sum( [TRX_MC_FOR_25]) As brpv_trx_mc_for_25,
       Sum( [TRX_MC_NAC_5_25]) As brpv_trx_mc_nac_5_25,
       Sum( [TRX_MC_NAC_25_100]) As brpv_trx_mc_nac_25_100,
       Sum( [TRX_MC_NAC_100]) As brpv_trx_mc_nac_100,
       Sum( [VI_TRX_FOR_6393101VARNP]) As brpv_vi_trx_for_6393101varnp,
       Sum( [VI_TRX_FOR_6393101VARP]) As brpv_vi_trx_for_6393101varp,
       Sum( [VI_TRX_FOR_6393207VARNP]) As brpv_vi_trx_for_6393207varnp,
       Sum( [VI_TRX_FOR_6393207VARP]) As brpv_vi_trx_for_6393207varp,
       Sum( [VI_TRX_FOR_6393217VARNP]) As brpv_vi_trx_for_6393217varnp,
       Sum( [VI_TRX_FOR_6393217VARP]) As brpv_vi_trx_for_6393217varp,
       Sum( [VI_TRX_FOR_6393218VARNP]) As brpv_vi_trx_for_6393218varnp,
       Sum( [VI_TRX_FOR_6393218VARP]) As brpv_vi_trx_for_6393218varp,
       Sum( [VI_TRX_FOR_6393222FIJONP]) As brpv_vi_trx_for_6393222fijonp,
       Sum( [VI_TRX_FOR_6393222FIJOP]) As brpv_vi_trx_for_6393222fijop,
       Sum( [VI_TRX_FOR_6393237VARNP]) As brpv_vi_trx_for_6393237varnp,
       Sum( [VI_TRX_FOR_6393237VARP]) As brpv_vi_trx_for_6393237varp,
       Sum( [VI_TRX_NAC_6393102FIJONP]) As brpv_vi_trx_nac_6393102fijonp,
       Sum( [VI_TRX_NAC_6393102FIJOP]) As brpv_vi_trx_nac_6393102fijop,
       Sum( [VI_TRX_NAC_6393202VARNP]) As brpv_vi_trx_nac_6393202varnp,
       Sum( [VI_TRX_NAC_6393202VARP]) As brpv_vi_trx_nac_6393202varp,
       Sum( [VI_TRX_NAC_6393236VARNP]) As brpv_vi_trx_nac_6393236varnp,
       Sum( [VI_TRX_NAC_6393236VARP]) As brpv_vi_trx_nac_6393236varp,
       Sum( [VI_TRX_NAC_6393238VARNP]) As brpv_vi_trx_nac_6393238varnp,
       Sum( [VI_TRX_NAC_6393238VARP]) As brpv_vi_trx_nac_6393238varp,
       Sum( [VI_TRX_NAC_6393240VARNP]) As brpv_vi_trx_nac_6393240varnp,
       Sum( [VI_TRX_NAC_6393240VARP]) As brpv_vi_trx_nac_6393240varp,
       Sum( [VI_TRX_TOT_6393201FIJONP]) As brpv_vi_trx_tot_6393201fijonp,
       Sum( [VI_TRX_TOT_6393201FIJOP]) As brpv_vi_trx_tot_6393201fijop,
       Sum( [VI_VOL_CRE_NAC_6393212VARNP]) As brpv_vi_vol_cre_nac_6393212varnp,
       Sum( [VI_VOL_DEB_NAC_6393220VARNP]) As brpv_vi_vol_deb_nac_6393220varnp,
       Sum( [VI_VOL_FOR_6393103VARNP]) As brpv_vi_vol_for_6393103varnp,
       Sum( [VI_VOL_FOR_6393103VARP]) As brpv_vi_vol_for_6393103varp,
       Sum( [VI_VOL_FOR_6393241VARNP]) As brpv_vi_vol_for_6393241varnp,
       Sum( [VI_VOL_FOR_6393241VARP]) As brpv_vi_vol_for_6393241varp,
       Sum( [VI_VOL_FOR_6393242VARNP]) As brpv_vi_vol_for_6393242varnp,
       Sum( [VI_VOL_FOR_6393242VARP]) As brpv_vi_vol_for_6393242varp,
       Sum( [VI_VOL_FOR_6393243VARNP]) As brpv_vi_vol_for_6393243varnp,
       Sum( [VI_VOL_FOR_6393243VARP]) As brpv_vi_vol_for_6393243varp,
       Sum( [VI_VOL_FOR_6393245VARNP]) As brpv_vi_vol_for_6393245varnp,
       Sum( [VI_VOL_FOR_6393245VARP]) As brpv_vi_vol_for_6393245varp,
       Sum( [VI_VOL_TOT_6393208FIJONP]) As brpv_vi_vol_tot_6393208fijonp,
       Sum( [VI_VOL_TOT_6393208FIJOP]) As brpv_vi_vol_tot_6393208fijop,
       Sum( [VI_VOL_TOT_6393210FIJONP]) As brpv_vi_vol_tot_6393210fijonp,
       Sum( [VI_VOL_TOT_6393210FIJOP]) As brpv_vi_vol_tot_6393210fijop,
       Sum( [VI_VOL_TOT_6393213FIJONP]) As brpv_vi_vol_tot_6393213fijonp,
       Sum( [VI_VOL_TOT_6393213FIJOP]) As brpv_vi_vol_tot_6393213fijop,
       Sum( [VI_VOL_TOT_6393214FIJONP]) As brpv_vi_vol_tot_6393214fijonp,
       Sum( [VI_VOL_TOT_6393214FIJOP]) As brpv_vi_vol_tot_6393214fijop,
       Sum( [VI_VOL_TOT_6393216FIJONP]) As brpv_vi_vol_tot_6393216fijonp,
       Sum( [VI_VOL_TOT_6393216FIJOP]) As brpv_vi_vol_tot_6393216fijop,
       Sum( [VI_VOL_TOT_6393216VARNP]) As brpv_vi_vol_tot_6393216varnp,
       Sum( [VI_VOL_TOT_6393216VARP]) As brpv_vi_vol_tot_6393216varp,
       Sum( [VI_VOL_TOT_6393219VARNP]) As brpv_vi_vol_tot_6393219varnp,
       Sum( [VI_VOL_TOT_6393219VARP]) As brpv_vi_vol_tot_6393219varp,
       Sum( [VI_VOL_TOT_NP_6393239VARNP]) As brpv_vi_vol_tot_np_6393239varnp,
       Sum( [VI_VD0_VD1_6393225VARNP]) As brpv_vi_vd0_vd1_6393225varnp,
       Sum( [VI_VD0_VD1_6393310VARNP]) As brpv_vi_vd0_vd1_6393310varnp,
       Sum( [VI_VD0_VD1_6393312VARNP]) As brpv_vi_vd0_vd1_6393312varnp,
       Sum( [VI_VD2_6393311VARNP]) As brpv_vi_vd2_6393311varnp,
       Sum( [VI_VD3_6393309VARNP]) As brpv_vi_vd3_6393309varnp,
       Sum( [VI_VD4_6393307VARNP]) As brpv_vi_vd4_6393307varnp,
       Sum( [VI_VD5_6393306VARNP]) As brpv_vi_vd5_6393306varnp,
       Sum( [VI_VD6_6393308VARNP]) As brpv_vi_vd6_6393308varnp,
       Sum( [VI_VD7_6393308VARNP]) As brpv_vi_vd7_6393308varnp,
       Sum( [MC_TRX_FOR_6393254VARNP]) As brpv_mc_trx_for_6393254varnp,
       Sum( [MC_TRX_FOR_6393256VARP]) As brpv_mc_trx_for_6393256varp,
       Sum( [MC_TRX_FOR_6393259VARP]) As brpv_mc_trx_for_6393259varp,
       Sum( [MC_TRX_FOR_6393268VARNP]) As brpv_mc_trx_for_6393268varnp,
       Sum( [MC_TRX_FOR_6393271VARNP]) As brpv_mc_trx_for_6393271varnp,
       Sum( [MC_TRX_FOR_6393273VARNP]) As brpv_mc_trx_for_6393273varnp,
       Sum( [MC_TRX_FOR_6393273VARP]) As brpv_mc_trx_for_6393273varp,
       Sum( [MC_TRX_FOR_6393277VARNP]) As brpv_mc_trx_for_6393277varnp,
       Sum( [MC_TRX_FOR_6393278VARNP]) As brpv_mc_trx_for_6393278varnp,
       Sum( [MC_TRX_FOR_6393283VARNP]) As brpv_mc_trx_for_6393283varnp,
       Sum( [MC_TRX_FOR_6393283VARP]) As brpv_mc_trx_for_6393283varp,
       Sum( [MC_TRX_FOR_6393284VARNP]) As brpv_mc_trx_for_6393284varnp,
       Sum( [MC_TRX_FOR_6393288FIJONP]) As brpv_mc_trx_for_6393288fijonp,
       Sum( [MC_TRX_FOR_NP_6393255VARNP]) As brpv_mc_trx_for_np_6393255varnp,
       Sum( [MC_TRX_FOR_NP_6393255VARP]) As brpv_mc_trx_for_np_6393255varp,
       Sum( [MC_TRX_FOR_NP_6393256VARP]) As brpv_mc_trx_for_np_6393256varp,
       Sum( [MC_TRX_FOR_NP_6393286VARP]) As brpv_mc_trx_for_np_6393286varp,
       Sum( [MC_TRX_NAC_6393254VARNP]) As brpv_mc_trx_nac_6393254varnp,
       Sum( [MC_TRX_NAC_6393256VARP]) As brpv_mc_trx_nac_6393256varp,
       Sum( [MC_TRX_NAC_6393258VARP]) As brpv_mc_trx_nac_6393258varp,
       Sum( [MC_TRX_NAC_6393267VARNP]) As brpv_mc_trx_nac_6393267varnp,
       Sum( [MC_TRX_NAC_6393272VARNP]) As brpv_mc_trx_nac_6393272varnp,
       Sum( [MC_TRX_NAC_6393274VARNP]) As brpv_mc_trx_nac_6393274varnp,
       Sum( [MC_TRX_NAC_6393283VARP]) As brpv_mc_trx_nac_6393283varp,
       Sum( [MC_TRX_NAC_6393285VARNP]) As brpv_mc_trx_nac_6393285varnp,
       Sum( [MC_TRX_NAC_6393289FIJONP]) As brpv_mc_trx_nac_6393289fijonp,
       Sum( [MC_TRX_NAC_NP_6393255VARP]) As brpv_mc_trx_nac_np_6393255varp,
       Sum( [MC_TRX_NAC_NP_6393256VARP]) As brpv_mc_trx_nac_np_6393256varp,
       Sum( [MC_TRX_NAC_NP_6393287VARP]) As brpv_mc_trx_nac_np_6393287varp,
       Sum( [MC_TRX_TOT_6393257FIJOP]) As brpv_mc_trx_tot_6393257fijop,
       Sum( [MC_TRX_TOT_6393279FIJONP]) As brpv_mc_trx_tot_6393279fijonp,
       Sum( [MC_TRX_TOT_6393281VARP]) As brpv_mc_trx_tot_6393281varp,
       Sum( [MC_VOL_CRE_NAC_6393280VARNP]) As brpv_mc_vol_cre_nac_6393280varnp,
       Sum( [MC_VOL_DEB_NAC_6393269VARNP]) As brpv_mc_vol_deb_nac_6393269varnp,
       Sum( [MC_VOL_FOR_6393256VARP]) As brpv_mc_vol_for_6393256varp,
       Sum( [MC_VOL_FOR_6393266VARNP]) As brpv_mc_vol_for_6393266varnp,
       Sum( [MC_VOL_FOR_6393284VARNP]) As brpv_mc_vol_for_6393284varnp,
       Sum( [MC_VOL_FOR_NP_6393255VARNP]) As brpv_mc_vol_for_np_6393255varnp,
       Sum( [MC_VOL_FOR_NP_6393255VARP]) As brpv_mc_vol_for_np_6393255varp,
       Sum( [MC_VOL_FOR_NP_6393256VARP]) As brpv_mc_vol_for_np_6393256varp,
       Sum( [MC_VOL_NAC_6393255VARP]) As brpv_mc_vol_nac_6393255varp,
       Sum( [MC_VOL_NAC_6393256VARP]) As brpv_mc_vol_nac_6393256varp,
       Sum( [MC_VOL_NAC_6393270VARNP]) As brpv_mc_vol_nac_6393270varnp,
       Sum( [MC_VOL_NAC_6393275VARNP]) As brpv_mc_vol_nac_6393275varnp,
       Sum( [MC_VOL_NAC_6393285VARNP]) As brpv_mc_vol_nac_6393285varnp,
       Sum( [MC_VOL_NAC_NP_6393255VARNP]) As brpv_mc_vol_nac_np_6393255varnp,
       Sum( [MC_VOL_NAC_NP_6393256VARP]) As brpv_mc_vol_nac_np_6393256varp,
       Sum( [MC_VOL_TOT_6393250FIJONP]) As brpv_mc_vol_tot_6393250fijonp,
       Sum( [MC_VOL_TOT_6393251FIJONP]) As brpv_mc_vol_tot_6393251fijonp,
       Sum( [MC_VOL_TOT_6393252FIJOP]) As brpv_mc_vol_tot_6393252fijop,
       Sum( [MC_VOL_TOT_6393253FIJONP]) As brpv_mc_vol_tot_6393253fijonp,
       Sum( [MC_VOL_TOT_6393276FIJONP]) As brpv_mc_vol_tot_6393276fijonp,
       Sum( [MC_VOL_TOT_6393282VARNP]) As brpv_mc_vol_tot_6393282varnp,
       Sum( [MC_VOL_TOT_6393283FIJONP]) As brpv_mc_vol_tot_6393283fijonp,
       Sum( [MC_VOL_TOT_6393283VARNP]) As brpv_mc_vol_tot_6393283varnp,
       Sum( [Monto_Invenio]) As brpv_monto_invenio,
       Sum( [Monto_Geopagos]) As brpv_monto_geopagos,
       Sum( [Cost_Personal_Middle]) As brpv_cost_personal_middle,
       Sum( [TRX_VI_CRE_NAC_NP_0_2]) As brpv_trx_vi_cre_nac_np_0_2,
       Sum( [TRX_VI_CRE_NAC_NP_2_5]) As brpv_trx_vi_cre_nac_np_2_5,
       Sum( [TRX_VI_CRE_NAC_NP_5_15]) As brpv_trx_vi_cre_nac_np_5_15,
       Sum( [TRX_VI_CRE_NAC_NP_15_50]) As brpv_trx_vi_cre_nac_np_15_50,
       Sum( [TRX_VI_CRE_NAC_NP_50]) As brpv_trx_vi_cre_nac_np_50,
       Sum( [TRX_VI_DEB_NAC_NP_0_2]) As brpv_trx_vi_deb_nac_np_0_2,
       Sum( [TRX_VI_DEB_NAC_NP_2_5]) As brpv_trx_vi_deb_nac_np_2_5,
       Sum( [TRX_VI_DEB_NAC_NP_5_15]) As brpv_trx_vi_deb_nac_np_5_15,
       Sum( [TRX_VI_DEB_NAC_NP_15_50]) As brpv_trx_vi_deb_nac_np_15_50,
       Sum( [TRX_VI_DEB_NAC_NP_50]) As brpv_trx_vi_deb_nac_np_50,
       Sum( [Costo_Portafolio_Comercio]) As brpv_costo_portafolio_comercio,
       Sum( [Costo_Portafolio_Cuc]) As brpv_costo_portafolio_cuc,
       --Sum( CostoVarTrxsMoneySend) As brpv_costo_var_trxs_money_send,
         0 As brpv_costo_var_trxs_money_send,
       Sum( [Digitacion_Monitoreo]) As brpv_digitacion_monitoreo,
       Sum( [DCC_Cuotas]) As brpv_dcc_cuotas,
       Sum( [DCC_Fee]) As brpv_dcc_fee,
       Sum( [DCC_Risk]) As brpv_dcc_risk,
       Sum( [COSTO_PORTAFOLIO_CODIGOCOMERCIO_PDV]) As brpv_costo_portafolio_codigocomercio_pdv,
       Sum( [COSTO_PORTAFOLIO_CODIGOCOMERCIO_RET]) As brpv_costo_portafolio_codigocomercio_ret,
       Sum( [COSTO_PORTAFOLIO_CODIGOCOMERCIO_PRO]) As brpv_costo_portafolio_codigocomercio_pro,
       Sum( [COSTO_PORTAFOLIO_CODIGOCOMERCIO_GRO]) As brpv_costo_portafolio_codigocomercio_gro,
       Sum( [COSTO_PORTAFOLIO_CODIGOCOMERCIO_HOT]) As brpv_costo_portafolio_codigocomercio_hot,
       Sum( [COSTO_PORTAFOLIO_CODIGOCOMERCIO_PS]) As brpv_costo_portafolio_codigocomercio_ps,
       Sum( [COSTO_PORTAFOLIO_CODIGOCOMERCIO_TAW]) As brpv_costo_portafolio_codigocomercio_taw,
       Sum( [COSTO_PORTAFOLIO_CUC_PDV]) As brpv_costo_portafolio_cuc_pdv,
       Sum( [COSTO_PORTAFOLIO_CUC_RET]) As brpv_costo_portafolio_cuc_ret,
       Sum( [COSTO_PORTAFOLIO_CUC_PRO]) As brpv_costo_portafolio_cuc_pro,
       Sum( [COSTO_PORTAFOLIO_CUC_GRO]) As brpv_costo_portafolio_cuc_gro,
       Sum( [COSTO_PORTAFOLIO_CUC_HOT]) As brpv_costo_portafolio_cuc_hot,
       Sum( [COSTO_PORTAFOLIO_CUC_PS]) As brpv_costo_portafolio_cuc_ps,
       Sum( [COSTO_PORTAFOLIO_CUC_TAW]) As brpv_costo_portafolio_cuc_taw,
       Sum( [Desarrollo_OPE]) As brpv_desarrollo_ope,
       Sum( [Desarrollo_SOPORTE]) As brpv_desarrollo_soporte,
       Sum( [Desarrollo_TEC]) As brpv_desarrollo_tec,
       Sum( [Desarrollo_SSCC]) As brpv_desarrollo_sscc,
       Sum( [Gasto_CallCenter_Pool]) As brpv_gasto_callcenter_pool,
       Sum( [TELECARGA_LICENCIA_TMS_MONTO]) As brpv_telecarga_licencia_tms_monto,
       Sum( [TELECARGA_ESTATEMANAGER_MONTO]) As brpv_telecarga_estatemanager_monto,
       Sum( [TELECARGA_ONTETIME_MONTO]) As brpv_telecarga_ontetime_monto,
       Sum( [DepreciacionActiva]) As brpv_depreciacion_activa,
       Sum( [DepreciacionInactiva]) As brpv_depreciacion_inactiva,
       Sum( [DepreciacionProvision]) As brpv_depreciacion_provision,
       Sum( [DevolucionesAverias]) As brpv_devoluciones_averias,
       Sum( [GastoCorrespondencia]) As brpv_gasto_correspondencia,
       Sum( [MRDP_Laboratorio]) As brpv_mrdp_laboratorio,
       Sum( [MRDP_Llamadas]) As brpv_mrdp_llamadas,
       Sum( [MRDP_Atenciones]) As brpv_mrdp_atenciones,
       Sum( [MRDP_Parque]) As brpv_mrdp_parque,
       Sum( [Trx_SAS_Pos]) As brpv_trx_sas_pos,
       Sum( [Trx_SAS_Pre]) As brpv_trx_sas_pre,
       Sum( [Publicidad_Costo_MKT]) As brpv_publicidad_costo_mkt,
       Sum( [Publicidad_Costo_Portafolio]) As brpv_publicidad_costo_portafolio,
       Sum( [IngresoAporteVISAPortafolio]) As brpv_ingreso_aportevisa_portafolio,
       Sum( [Gasto_SAS_Pre]) As brpv_gasto_sas_pre,
       Sum( [Gasto_SAS_Pos]) As brpv_gasto_sas_pos,
       Sum( [Gasto_SAS_Pre_Pos]) As brpv_gasto_sas_pre_pos,
       Sum( [GastoEventualRemplazo_Seg]) As brpv_gasto_eventual_remplazo_seg,
       Sum( [GastoAlquilerAlmacen]) As brpv_gasto_alquiler_almacen,
       Sum( [IngresoAveriaContometro]) As brpv_ingreso_averia_contometro,
       Sum( [GastoCyberSource]) As brpv_gasto_cyber_source,
       Sum( [Cost_Call_Afil]) As brpv_cost_call_afil,
       Sum( [Gasto_Portafolio_Segmento]) As brpv_gasto_portafolio_segmento,
       Sum( [Ingreso_Vendemas_RYS]) As brpv_ingreso_vendemas_rys,
       Sum( [Costo_Vendemas_RYS]) As brpv_costo_vendemas_rys,
       Sum( [Ingreso_Niubiz_RYS]) As brpv_ingreso_niubiz_rys,
       Sum( [Costo_Niubiz_RYS]) As brpv_costo_niubiz_rys,
       Sum( [Gasto_Afiliacion_Real]) As brpv_gasto_afiliacion_real,
       Sum( [Gasto_Afiliacion_Provision]) As brpv_gasto_afiliacion_provision,
       Sum( [Gasto_Afiliacion_Extorno]) As brpv_gasto_afiliacion_extorno,
       Sum( [Gasto_Cuotas_Fee_Anual_VI]) As brpv_gasto_cuotas_fee_anual_vi,
       Sum( [Gasto_Cuotas_PIPF_VI]) As brpv_gasto_cuotas_pipf_vi,
       Sum( [Gasto_Cuotas_Multas_VI]) As brpv_gasto_cuotas_multas_vi,
       Sum( [Gasto_Cuotas_Suscripciones_VI]) As brpv_gasto_cuotas_suscripciones_vi,
       Sum( [Gasto_Reintentos_VI]) As brpv_gasto_reintentos_vi,
       Sum( [Gasto_Cuotas_Fee_Anual_MC]) As brpv_gasto_cuotas_fee_anual_mc,
       Sum( [Gasto_Cuotas_PIPF_MC]) As brpv_gasto_cuotas_pipf_mc,
       Sum( [Gasto_Cuotas_Multas_MC]) As brpv_gasto_cuotas_multas_mc,
       Sum( [Gasto_Cuotas_Suscripciones_MC]) As brpv_gasto_cuotas_suscripciones_mc,
       Sum( [Gasto_Reintentos_MC]) As brpv_gasto_reintentos_mc,
       Sum( [Gasto_CobroPagos]) As brpv_gasto_cobro_pagos,
       Sum( [VI_TRX_NAC_6393244VARNP]) As brpv_vi_trx_nac_6393244varn
  From NIUBIZ_DEV.BASE_RENTA_NBZ_VMAS_X_TERMINAL
 Where PERIODO = 202608 AND  FUENTE ='Niubiz' --and CODIGOCOMERCIO = 651058060 AND TERMINAL ='93189347'

 Group By PERIODO,
       FUENTE
		 --CODIGOCOMERCIO,
		 --TERMINAL





select brpv_periodo  ,
   brpv_fuente ,
   --brpv_codigo_comercio,
   sum( brpv_vol_tot)  as brpv_vol_to ,
   sum( brpv_txs_tot)  as brpv_txs_tot ,
   sum( brpv_ct_tot)  as brpv_ct_tot ,
   sum( brpv_cv_tot)  as brpv_cv_tot ,
   sum( brpv_vol_nacional)  as brpv_vol_nacional ,
   sum( brpv_txn_nacional)  as brpv_txn_nacional ,
   sum( brpv_vol_internacional)  as brpv_vol_internacional ,
   sum( brpv_txn_internacional)  as brpv_txn_internacional ,
   sum( brpv_vol_cen)  as brpv_vol_cen ,
   sum( brpv_vol_cei)  as brpv_vol_cei ,
   sum( brpv_vol_dn)  as brpv_vol_dn ,
   sum( brpv_vol_di)  as brpv_vol_di ,
   sum( brpv_vol_cmn)  as brpv_vol_cmn ,
   sum( brpv_vol_cmi)  as brpv_vol_cmi ,
   sum( brpv_txs_cen)  as brpv_txs_cen ,
   sum( brpv_txs_cei)  as brpv_txs_cei ,
   sum( brpv_txs_dn)  as brpv_txs_dn ,
   sum( brpv_txs_di)  as brpv_txs_di ,
   sum( brpv_txs_cmn)  as brpv_txs_cmn ,
   sum( brpv_txs_cmi)  as brpv_txs_cmi ,
   sum( brpv_ct_cen)  as brpv_ct_cen ,
   sum( brpv_ct_cei)  as brpv_ct_cei ,
   sum( brpv_ct_dn)  as brpv_ct_dn ,
   sum( brpv_ct_di)  as brpv_ct_di ,
   sum( brpv_ct_cmn)  as brpv_ct_cmn ,
   sum( brpv_ct_cmi)  as brpv_ct_cmi ,
   sum( brpv_cv_cen)  as brpv_cv_cen ,
   sum( brpv_cv_cei)  as brpv_cv_cei ,
   sum( brpv_cv_dn)  as brpv_cv_dn ,
   sum( brpv_cv_di)  as brpv_cv_di ,
   sum( brpv_cv_cmn)  as brpv_cv_cmn ,
   sum( brpv_cv_cmi)  as brpv_cv_cmi ,
   sum( brpv_vol_hib)  as brpv_vol_hib ,
   sum( brpv_fee_txs_fee)  as brpv_fee_txs_fee ,
   sum( brpv_enf)  as brpv_enf ,
   sum( brpv_tkt)  as brpv_tkt ,
   sum( brpv_com_total)  as brpv_com_total ,
   sum( brpv_com_vsnt1l)  as brpv_com_vsnt1l ,
   sum( brpv_t_interc)  as brpv_t_interc ,
   sum( brpv_com_emi_tot)  as brpv_com_emi_tot ,
   sum( brpv_com_emi_loc)  as brpv_com_emi_loc ,
   sum( brpv_com_emi_for)  as brpv_com_emi_for ,
   sum( brpv_dcc_costo)  as brpv_dcc_costo ,
   sum( brpv_dcc_ingreso)  as brpv_dcc_ingreso ,
   sum( brpv_l0800_costo)  as brpv_l0800_costo ,
   sum( brpv_l0800_ingreso)  as brpv_l0800_ingreso ,
   sum( brpv_eecc_ingreso)  as brpv_eecc_ingreso ,
   sum( brpv_eecc_costo)  as brpv_eecc_costo ,
   sum( brpv_alquiler_ingreso)  as brpv_alquiler_ingreso ,
   sum( brpv_preautorizacion_ingreso)  as brpv_preautorizacion_ingreso ,
   sum( brpv_robos_ingreso)  as brpv_robos_ingreso ,
   sum( brpv_visitas_costo)  as brpv_visitas_costo ,
   sum( brpv_afiliacion_costo)  as brpv_afiliacion_costo ,
   sum( brpv_depreciacion_costo)  as brpv_depreciacion_costo ,
   sum( brpv_chips_costo)  as brpv_chips_costo ,
   sum( brpv_personal_costo)  as brpv_personal_costo ,
   sum( brpv_publicidad_costo)  as brpv_publicidad_costo ,
   sum( brpv_testing_factory_costo)  as brpv_testing_factory_costo ,
   sum( brpv_desarrollo_costo)  as brpv_desarrollo_costo ,
   sum( brpv_reparacion_accesorios)  as brpv_reparacion_accesorios ,
   sum( brpv_recupero_costo)  as brpv_recupero_costo ,
   sum( brpv_instalacion_costo)  as brpv_instalacion_costo ,
   sum( brpv_telecarga_costo)  as brpv_telecarga_costo ,
   sum( brpv_suministro_costo)  as brpv_suministro_costo ,
   sum( brpv_com_vsnt)  as brpv_com_vsnt ,
   sum( brpv_c_var_txs_total)  as brpv_c_var_txs_total ,
   sum( brpv_cost_infraestructura)  as brpv_cost_infraestructura ,
   sum( brpv_cost_licencia_e_core)  as brpv_cost_licencia_e_core ,
   sum( brpv_cost_monitoreo)  as brpv_cost_monitoreo ,
   sum( brpv_cost_soporte)  as brpv_cost_soporte ,
   sum( brpv_personal_adecco)  as brpv_personal_adecco ,
   sum( brpv_cost_autenticacion)  as brpv_cost_autenticacion ,
   sum( brpv_ingreso_poket)  as brpv_ingreso_poket ,
   sum( brpv_cost_poket)  as brpv_cost_poket ,
   sum( brpv_cost_cybersource)  as brpv_cost_cybersource ,
   sum( brpv_ing_cybersource)  as brpv_ing_cybersource ,
   sum( brpv_ing_renovacion)  as brpv_ing_renovacion ,
   sum( brpv_cost_agentetercero)  as brpv_cost_agentetercero ,
   sum( brpv_inc_agentetercero)  as brpv_inc_agentetercero ,
   sum( brpv_cost_verifiedbyvisa)  as brpv_cost_verifiedbyvisa ,
   sum( brpv_cost_geopagos)  as brpv_cost_geopagos ,
   sum( brpv_cost_tercerizado)  as brpv_cost_tercerizado ,
   sum( brpv_ing_afiliaciones)  as brpv_ing_afiliaciones ,
   sum( brpv_ingreso_por_mantenimiento)  as brpv_ingreso_por_mantenimiento ,
   sum( brpv_ingreso_por_renovacion)  as brpv_ingreso_por_renovacion ,
   sum( brpv_ingreso_por_transaccion)  as brpv_ingreso_por_transaccion ,
   sum( brpv_costo_envio_poket)  as brpv_costo_envio_poket ,
   sum( brpv_costo_alignet)  as brpv_costo_alignet ,
   sum( brpv_costo_amortizaciones)  as brpv_costo_amortizaciones ,
   sum( brpv_afiliacion_rec)  as brpv_afiliacion_rec ,
   sum( brpv_mantenimiento_rec)  as brpv_mantenimiento_rec ,
   sum( brpv_otros_rdp)  as brpv_otros_rdp ,
   sum( brpv_ferias_y_eventos)  as brpv_ferias_y_eventos ,
   sum( brpv_impr_laser)  as brpv_impr_laser ,
   sum( brpv_insta_diaria_express)  as brpv_insta_diaria_express ,
   sum( brpv_insta_eventos_express)  as brpv_insta_eventos_express ,
   sum( brpv_mpos_rdp)  as brpv_mpos_rdp ,
   sum( brpv_cost_contometro)  as brpv_cost_contometro ,
   sum( brpv_cost_migraciones)  as brpv_cost_migraciones ,
   sum( brpv_ing_fee_membresia)  as brpv_ing_fee_membresia ,
   sum( brpv_cost_plugin)  as brpv_cost_plugin ,
   sum( brpv_ingreso_setup)  as brpv_ingreso_setup ,
   sum( brpv_replugin)  as brpv_replugin ,
   sum( brpv_ingreso_refacturacion_mkt)  as brpv_ingreso_refacturacion_mkt ,
   sum( brpv_ingreso_refacturacion_servicios)  as brpv_ingreso_refacturacion_servicios ,
   sum( brpv_ingreso_aporte_visa_mkt)  as brpv_ingreso_aporte_visa_mkt ,
   sum( brpv_gasto_refacturacion_mkt)  as brpv_gasto_refacturacion_mkt ,
   sum( brpv_gasto_refacturacion_servicios)  as brpv_gasto_refacturacion_servicios ,
   sum( brpv_gasto_aporte_visa_mkt)  as brpv_gasto_aporte_visa_mkt ,
   sum( brpv_afiliacion_generado_costo)  as brpv_afiliacion_generado_costo ,
   sum( brpv_afiliacion_habilitado_costo)  as brpv_afiliacion_habilitado_costo ,
   sum( brpv_afiliacion_cpa_corporativo_dcc)  as brpv_afiliacion_cpa_corporativo_dcc ,
   sum( brpv_afiliacion_cpa_variable_dcc)  as brpv_afiliacion_cpa_variable_dcc ,
   sum( brpv_afiliacion_cpa_digit_monit)  as brpv_afiliacion_cpa_digit_monit ,
   sum( brpv_ingreso_trxs_vendomatica)  as brpv_ingreso_trxs_vendomatica ,
   sum( brpv_ingreso_gobierno)  as brpv_ingreso_gobierno ,
   sum( brpv_incobrable)  as brpv_incobrable ,
   sum( brpv_fee_transporte)  as brpv_fee_transporte ,
   sum( brpv_gasto_postventa)  as brpv_gasto_postventa ,
   sum( brpv_transacciones_data)  as brpv_transacciones_data ,
   sum( brpv_pos_cobrar)  as brpv_pos_cobrar ,
   sum( brpv_tarjetas)  as brpv_tarjetas ,
   sum( brpv_ingresos_transacciones_data)  as brpv_ingresos_transacciones_data ,
   sum( brpv_ingresos_pos_activo)  as brpv_ingresos_pos_activo ,
   sum( brpv_ingresos_tarjetas)  as brpv_ingresos_tarjetas ,
   sum( brpv_ingresos_soluciones_fraude)  as brpv_ingresos_soluciones_fraude ,
   sum( brpv_ingresos_setup)  as brpv_ingresos_setup ,
   sum( brpv_ingresos_mantenimiento)  as brpv_ingresos_mantenimiento ,
   sum( brpv_otros_ingresos)  as brpv_otros_ingresos ,
   sum( brpv_otros_gastos_servicios)  as brpv_otros_gastos_servicios ,
   sum( brpv_gasto_producto)  as brpv_gasto_producto ,
   sum( brpv_gasto_flotas)  as brpv_gasto_flotas ,
   sum( brpv_niif_afiliacion)  as brpv_niif_afiliacion ,
   sum( brpv_niif_subsidio)  as brpv_niif_subsidio ,
   sum( brpv_ingresos_izipay)  as brpv_ingresos_izipay ,
   sum( brpv_gastos_izipay)  as brpv_gastos_izipay ,
   sum( brpv_costo_procesamiento)  as brpv_costo_procesamiento ,
   sum( brpv_ingresos_recargas_servicios)  as brpv_ingresos_recargas_servicios ,
   sum( brpv_gasto_recargas_servicios)  as brpv_gasto_recargas_servicios ,
   sum( brpv_ingresos_prestamos)  as brpv_ingresos_prestamos ,
   sum( brpv_ingresos_peajes)  as brpv_ingresos_peajes ,
   sum( brpv_costo_cupo)  as brpv_costo_cupo ,
   sum( brpv_gasto_eventual_remplazo)  as brpv_gasto_eventual_remplazo ,
   sum( brpv_gasto_sig)  as brpv_gasto_sig ,
   sum( brpv_gasto_cross_niubiz)  as brpv_gasto_cross_niubiz ,
   sum( brpv_personal_costo_procesamiento)  as brpv_personal_costo_procesamiento ,
   sum( brpv_costo_var_txs_visa_direct)  as brpv_costo_var_txs_visa_direct ,
   sum( brpv_costo_var_txs_visa)  as brpv_costo_var_txs_visa ,
   sum( brpv_costo_var_txs_mc)  as brpv_costo_var_txs_mc ,
   sum( brpv_gasto_nbo_procesamiento)  as brpv_gasto_nbo_procesamiento ,
   sum( brpv_gasto_canales)  as brpv_gasto_canales ,
   sum( brpv_gasto_comercio)  as brpv_gasto_comercio ,
   sum( brpv_costo_analytics)  as brpv_costo_analytics ,
   sum( brpv_costo_sas)  as brpv_costo_sas ,
   sum( brpv_gasto_amortizacion_sas)  as brpv_gasto_amortizacion_sas ,
   sum( brpv_peajes_procesam)  as brpv_peajes_procesam ,
   sum( brpv_gasto_cross_online)  as brpv_gasto_cross_online ,
   sum( brpv_gasto_cross_unidad)  as brpv_gasto_cross_unidad ,
   sum( brpv_contra_cargo)  as brpv_contra_cargo ,
   sum( brpv_gasto_alquiler_equipo)  as brpv_gasto_alquiler_equipo ,
   sum( brpv_gasto_controversias_asumidas)  as brpv_gasto_controversias_asumidas ,
   sum( brpv_trx_mc_for_1)  as brpv_trx_mc_for_1 ,
   sum( brpv_trx_mc_for_1_5)  as brpv_trx_mc_for_1_5 ,
   sum( brpv_trx_mc_for_5)  as brpv_trx_mc_for_5 ,
   sum( brpv_trx_mc_nac_1)  as brpv_trx_mc_nac_1 ,
   sum( brpv_trx_mc_nac_1_5)  as brpv_trx_mc_nac_1_5 ,
   sum( brpv_trx_mc_nac_10_25)  as brpv_trx_mc_nac_10_25 ,
   sum( brpv_trx_mc_nac_25)  as brpv_trx_mc_nac_25 ,
   sum( brpv_trx_mc_nac_5_10)  as brpv_trx_mc_nac_5_10 ,
   sum( brpv_trx_vi_cre_for_np_0_5)  as brpv_trx_vi_cre_for_np_0_5 ,
   sum( brpv_trx_vi_cre_for_np_100_250)  as brpv_trx_vi_cre_for_np_100_250 ,
   sum( brpv_trx_vi_cre_for_np_15_50)  as brpv_trx_vi_cre_for_np_15_50 ,
   sum( brpv_trx_vi_cre_for_np_250)  as brpv_trx_vi_cre_for_np_250 ,
   sum( brpv_trx_vi_cre_for_np_5_15)  as brpv_trx_vi_cre_for_np_5_15 ,
   sum( brpv_trx_vi_cre_for_np_50_100)  as brpv_trx_vi_cre_for_np_50_100 ,
   sum( brpv_trx_vi_cre_for_p_0_5)  as brpv_trx_vi_cre_for_p_0_5 ,
   sum( brpv_trx_vi_cre_for_p_100_250)  as brpv_trx_vi_cre_for_p_100_250 ,
   sum( brpv_trx_vi_cre_for_p_15_50)  as brpv_trx_vi_cre_for_p_15_50 ,
   sum( brpv_trx_vi_cre_for_p_250)  as brpv_trx_vi_cre_for_p_250 ,
   sum( brpv_trx_vi_cre_for_p_5_15)  as brpv_trx_vi_cre_for_p_5_15 ,
   sum( brpv_trx_vi_cre_for_p_50_100)  as brpv_trx_vi_cre_for_p_50_100 ,
   sum( brpv_trx_vi_cre_nac_p_0_2)  as brpv_trx_vi_cre_nac_p_0_2 ,
   sum( brpv_trx_vi_cre_nac_p_15_50)  as brpv_trx_vi_cre_nac_p_15_50 ,
   sum( brpv_trx_vi_cre_nac_p_2_5)  as brpv_trx_vi_cre_nac_p_2_5 ,
   sum( brpv_trx_vi_cre_nac_p_5_15)  as brpv_trx_vi_cre_nac_p_5_15 ,
   sum( brpv_trx_vi_cre_nac_p_50)  as brpv_trx_vi_cre_nac_p_50 ,
   sum( brpv_trx_vi_deb_for_np_0_5)  as brpv_trx_vi_deb_for_np_0_5 ,
   sum( brpv_trx_vi_deb_for_np_100_250)  as brpv_trx_vi_deb_for_np_100_250 ,
   sum( brpv_trx_vi_deb_for_np_15_50)  as brpv_trx_vi_deb_for_np_15_50 ,
   sum( brpv_trx_vi_deb_for_np_250)  as brpv_trx_vi_deb_for_np_250 ,
   sum( brpv_trx_vi_deb_for_np_5_15)  as brpv_trx_vi_deb_for_np_5_15 ,
   sum( brpv_trx_vi_deb_for_np_50_100)  as brpv_trx_vi_deb_for_np_50_100 ,
   sum( brpv_trx_vi_deb_for_p_0_5)  as brpv_trx_vi_deb_for_p_0_5 ,
   sum( brpv_trx_vi_deb_for_p_100_250)  as brpv_trx_vi_deb_for_p_100_250 ,
   sum( brpv_trx_vi_deb_for_p_15_50)  as brpv_trx_vi_deb_for_p_15_50 ,
   sum( brpv_trx_vi_deb_for_p_250)  as brpv_trx_vi_deb_for_p_250 ,
   sum( brpv_trx_vi_deb_for_p_5_15)  as brpv_trx_vi_deb_for_p_5_15 ,
   sum( brpv_trx_vi_deb_for_p_50_100)  as brpv_trx_vi_deb_for_p_50_100 ,
   sum( brpv_trx_vi_deb_nac_p_0_2)  as brpv_trx_vi_deb_nac_p_0_2 ,
   sum( brpv_trx_vi_deb_nac_p_15_50)  as brpv_trx_vi_deb_nac_p_15_50 ,
   sum( brpv_trx_vi_deb_nac_p_2_5)  as brpv_trx_vi_deb_nac_p_2_5 ,
   sum( brpv_trx_vi_deb_nac_p_5_15)  as brpv_trx_vi_deb_nac_p_5_15 ,
   sum( brpv_trx_vi_deb_nac_p_50)  as brpv_trx_vi_deb_nac_p_50 ,
   sum( brpv_trx_mc_for_5_menos)  as brpv_trx_mc_for_5_menos ,
   sum( brpv_trx_mc_for_5_25)  as brpv_trx_mc_for_5_25 ,
   sum( brpv_trx_mc_for_25)  as brpv_trx_mc_for_25 ,
   sum( brpv_trx_mc_nac_5_25)  as brpv_trx_mc_nac_5_25 ,
   sum( brpv_trx_mc_nac_25_100)  as brpv_trx_mc_nac_25_100 ,
   sum( brpv_trx_mc_nac_100)  as brpv_trx_mc_nac_100 ,
   sum( brpv_vi_trx_for_6393101varnp)  as brpv_vi_trx_for_6393101varnp ,
   sum( brpv_vi_trx_for_6393101varp)  as brpv_vi_trx_for_6393101varp ,
   sum( brpv_vi_trx_for_6393207varnp)  as brpv_vi_trx_for_6393207varnp ,
   sum( brpv_vi_trx_for_6393207varp)  as brpv_vi_trx_for_6393207varp ,
   sum( brpv_vi_trx_for_6393217varnp)  as brpv_vi_trx_for_6393217varnp ,
   sum( brpv_vi_trx_for_6393217varp)  as brpv_vi_trx_for_6393217varp ,
   sum( brpv_vi_trx_for_6393218varnp)  as brpv_vi_trx_for_6393218varnp ,
   sum( brpv_vi_trx_for_6393218varp)  as brpv_vi_trx_for_6393218varp ,
   sum( brpv_vi_trx_for_6393222fijonp)  as brpv_vi_trx_for_6393222fijonp ,
   sum( brpv_vi_trx_for_6393222fijop)  as brpv_vi_trx_for_6393222fijop ,
   sum( brpv_vi_trx_for_6393237varnp)  as brpv_vi_trx_for_6393237varnp ,
   sum( brpv_vi_trx_for_6393237varp)  as brpv_vi_trx_for_6393237varp ,
   sum( brpv_vi_trx_nac_6393102fijonp)  as brpv_vi_trx_nac_6393102fijonp ,
   sum( brpv_vi_trx_nac_6393102fijop)  as brpv_vi_trx_nac_6393102fijop ,
   sum( brpv_vi_trx_nac_6393202varnp)  as brpv_vi_trx_nac_6393202varnp ,
   sum( brpv_vi_trx_nac_6393202varp)  as brpv_vi_trx_nac_6393202varp ,
   sum( brpv_vi_trx_nac_6393236varnp)  as brpv_vi_trx_nac_6393236varnp ,
   sum( brpv_vi_trx_nac_6393236varp)  as brpv_vi_trx_nac_6393236varp ,
   sum( brpv_vi_trx_nac_6393238varnp)  as brpv_vi_trx_nac_6393238varnp ,
   sum( brpv_vi_trx_nac_6393238varp)  as brpv_vi_trx_nac_6393238varp ,
   sum( brpv_vi_trx_nac_6393240varnp)  as brpv_vi_trx_nac_6393240varnp ,
   sum( brpv_vi_trx_nac_6393240varp)  as brpv_vi_trx_nac_6393240varp ,
   sum( brpv_vi_trx_tot_6393201fijonp)  as brpv_vi_trx_tot_6393201fijonp ,
   sum( brpv_vi_trx_tot_6393201fijop)  as brpv_vi_trx_tot_6393201fijop ,
   sum( brpv_vi_vol_cre_nac_6393212varnp)  as brpv_vi_vol_cre_nac_6393212varnp ,
   sum( brpv_vi_vol_deb_nac_6393220varnp)  as brpv_vi_vol_deb_nac_6393220varnp ,
   sum( brpv_vi_vol_for_6393103varnp)  as brpv_vi_vol_for_6393103varnp ,
   sum( brpv_vi_vol_for_6393103varp)  as brpv_vi_vol_for_6393103varp ,
   sum( brpv_vi_vol_for_6393241varnp)  as brpv_vi_vol_for_6393241varnp ,
   sum( brpv_vi_vol_for_6393241varp)  as brpv_vi_vol_for_6393241varp ,
   sum( brpv_vi_vol_for_6393242varnp)  as brpv_vi_vol_for_6393242varnp ,
   sum( brpv_vi_vol_for_6393242varp)  as brpv_vi_vol_for_6393242varp ,
   sum( brpv_vi_vol_for_6393243varnp)  as brpv_vi_vol_for_6393243varnp ,
   sum( brpv_vi_vol_for_6393243varp)  as brpv_vi_vol_for_6393243varp ,
   sum( brpv_vi_vol_for_6393245varnp)  as brpv_vi_vol_for_6393245varnp ,
   sum( brpv_vi_vol_for_6393245varp)  as brpv_vi_vol_for_6393245varp ,
   sum( brpv_vi_vol_tot_6393208fijonp)  as brpv_vi_vol_tot_6393208fijonp ,
   sum( brpv_vi_vol_tot_6393208fijop)  as brpv_vi_vol_tot_6393208fijop ,
   sum( brpv_vi_vol_tot_6393210fijonp)  as brpv_vi_vol_tot_6393210fijonp ,
   sum( brpv_vi_vol_tot_6393210fijop)  as brpv_vi_vol_tot_6393210fijop ,
   sum( brpv_vi_vol_tot_6393213fijonp)  as brpv_vi_vol_tot_6393213fijonp ,
   sum( brpv_vi_vol_tot_6393213fijop)  as brpv_vi_vol_tot_6393213fijop ,
   sum( brpv_vi_vol_tot_6393214fijonp)  as brpv_vi_vol_tot_6393214fijonp ,
   sum( brpv_vi_vol_tot_6393214fijop)  as brpv_vi_vol_tot_6393214fijop ,
   sum( brpv_vi_vol_tot_6393216fijonp)  as brpv_vi_vol_tot_6393216fijonp ,
   sum( brpv_vi_vol_tot_6393216fijop)  as brpv_vi_vol_tot_6393216fijop ,
   sum( brpv_vi_vol_tot_6393216varnp)  as brpv_vi_vol_tot_6393216varnp ,
   sum( brpv_vi_vol_tot_6393216varp)  as brpv_vi_vol_tot_6393216varp ,
   sum( brpv_vi_vol_tot_6393219varnp)  as brpv_vi_vol_tot_6393219varnp ,
   sum( brpv_vi_vol_tot_6393219varp)  as brpv_vi_vol_tot_6393219varp ,
   sum( brpv_vi_vol_tot_np_6393239varnp)  as brpv_vi_vol_tot_np_6393239varnp ,
   sum( brpv_vi_vd0_vd1_6393225varnp)  as brpv_vi_vd0_vd1_6393225varnp ,
   sum( brpv_vi_vd0_vd1_6393310varnp)  as brpv_vi_vd0_vd1_6393310varnp ,
   sum( brpv_vi_vd0_vd1_6393312varnp)  as brpv_vi_vd0_vd1_6393312varnp ,
   sum( brpv_vi_vd2_6393311varnp)  as brpv_vi_vd2_6393311varnp ,
   sum( brpv_vi_vd3_6393309varnp)  as brpv_vi_vd3_6393309varnp ,
   sum( brpv_vi_vd4_6393307varnp)  as brpv_vi_vd4_6393307varnp ,
   sum( brpv_vi_vd5_6393306varnp)  as brpv_vi_vd5_6393306varnp ,
   sum( brpv_vi_vd6_6393308varnp)  as brpv_vi_vd6_6393308varnp ,
   sum( brpv_vi_vd7_6393308varnp)  as brpv_vi_vd7_6393308varnp ,
   sum( brpv_mc_trx_for_6393254varnp)  as brpv_mc_trx_for_6393254varnp ,
   sum( brpv_mc_trx_for_6393256varp)  as brpv_mc_trx_for_6393256varp ,
   sum( brpv_mc_trx_for_6393259varp)  as brpv_mc_trx_for_6393259varp ,
   sum( brpv_mc_trx_for_6393268varnp)  as brpv_mc_trx_for_6393268varnp ,
   sum( brpv_mc_trx_for_6393271varnp)  as brpv_mc_trx_for_6393271varnp ,
   sum( brpv_mc_trx_for_6393273varnp)  as brpv_mc_trx_for_6393273varnp ,
   sum( brpv_mc_trx_for_6393273varp)  as brpv_mc_trx_for_6393273varp ,
   sum( brpv_mc_trx_for_6393277varnp)  as brpv_mc_trx_for_6393277varnp ,
   sum( brpv_mc_trx_for_6393278varnp)  as brpv_mc_trx_for_6393278varnp ,
   sum( brpv_mc_trx_for_6393283varnp)  as brpv_mc_trx_for_6393283varnp ,
   sum( brpv_mc_trx_for_6393283varp)  as brpv_mc_trx_for_6393283varp ,
   sum( brpv_mc_trx_for_6393284varnp)  as brpv_mc_trx_for_6393284varnp ,
   sum( brpv_mc_trx_for_6393288fijonp)  as brpv_mc_trx_for_6393288fijonp ,
   sum( brpv_mc_trx_for_np_6393255varnp)  as brpv_mc_trx_for_np_6393255varnp ,
   sum( brpv_mc_trx_for_np_6393255varp)  as brpv_mc_trx_for_np_6393255varp ,
   sum( brpv_mc_trx_for_np_6393256varp)  as brpv_mc_trx_for_np_6393256varp ,
   sum( brpv_mc_trx_for_np_6393286varp)  as brpv_mc_trx_for_np_6393286varp ,
   sum( brpv_mc_trx_nac_6393254varnp)  as brpv_mc_trx_nac_6393254varnp ,
   sum( brpv_mc_trx_nac_6393256varp)  as brpv_mc_trx_nac_6393256varp ,
   sum( brpv_mc_trx_nac_6393258varp)  as brpv_mc_trx_nac_6393258varp ,
   sum( brpv_mc_trx_nac_6393267varnp)  as brpv_mc_trx_nac_6393267varnp ,
   sum( brpv_mc_trx_nac_6393272varnp)  as brpv_mc_trx_nac_6393272varnp ,
   sum( brpv_mc_trx_nac_6393274varnp)  as brpv_mc_trx_nac_6393274varnp ,
   sum( brpv_mc_trx_nac_6393283varp)  as brpv_mc_trx_nac_6393283varp ,
   sum( brpv_mc_trx_nac_6393285varnp)  as brpv_mc_trx_nac_6393285varnp ,
   sum( brpv_mc_trx_nac_6393289fijonp)  as brpv_mc_trx_nac_6393289fijonp ,
   sum( brpv_mc_trx_nac_np_6393255varp)  as brpv_mc_trx_nac_np_6393255varp ,
   sum( brpv_mc_trx_nac_np_6393256varp)  as brpv_mc_trx_nac_np_6393256varp ,
   sum( brpv_mc_trx_nac_np_6393287varp)  as brpv_mc_trx_nac_np_6393287varp ,
   sum( brpv_mc_trx_tot_6393257fijop)  as brpv_mc_trx_tot_6393257fijop ,
   sum( brpv_mc_trx_tot_6393279fijonp)  as brpv_mc_trx_tot_6393279fijonp ,
   sum( brpv_mc_trx_tot_6393281varp)  as brpv_mc_trx_tot_6393281varp ,
   sum( brpv_mc_vol_cre_nac_6393280varnp)  as brpv_mc_vol_cre_nac_6393280varnp ,
   sum( brpv_mc_vol_deb_nac_6393269varnp)  as brpv_mc_vol_deb_nac_6393269varnp ,
   sum( brpv_mc_vol_for_6393256varp)  as brpv_mc_vol_for_6393256varp ,
   sum( brpv_mc_vol_for_6393266varnp)  as brpv_mc_vol_for_6393266varnp ,
   sum( brpv_mc_vol_for_6393284varnp)  as brpv_mc_vol_for_6393284varnp ,
   sum( brpv_mc_vol_for_np_6393255varnp)  as brpv_mc_vol_for_np_6393255varnp ,
   sum( brpv_mc_vol_for_np_6393255varp)  as brpv_mc_vol_for_np_6393255varp ,
   sum( brpv_mc_vol_for_np_6393256varp)  as brpv_mc_vol_for_np_6393256varp ,
   sum( brpv_mc_vol_nac_6393255varp)  as brpv_mc_vol_nac_6393255varp ,
   sum( brpv_mc_vol_nac_6393256varp)  as brpv_mc_vol_nac_6393256varp ,
   sum( brpv_mc_vol_nac_6393270varnp)  as brpv_mc_vol_nac_6393270varnp ,
   sum( brpv_mc_vol_nac_6393275varnp)  as brpv_mc_vol_nac_6393275varnp ,
   sum( brpv_mc_vol_nac_6393285varnp)  as brpv_mc_vol_nac_6393285varnp ,
   sum( brpv_mc_vol_nac_np_6393255varnp)  as brpv_mc_vol_nac_np_6393255varnp ,
   sum( brpv_mc_vol_nac_np_6393256varp)  as brpv_mc_vol_nac_np_6393256varp ,
   sum( brpv_mc_vol_tot_6393250fijonp)  as brpv_mc_vol_tot_6393250fijonp ,
   sum( brpv_mc_vol_tot_6393251fijonp)  as brpv_mc_vol_tot_6393251fijonp ,
   sum( brpv_mc_vol_tot_6393252fijop)  as brpv_mc_vol_tot_6393252fijop ,
   sum( brpv_mc_vol_tot_6393253fijonp)  as brpv_mc_vol_tot_6393253fijonp ,
   sum( brpv_mc_vol_tot_6393276fijonp)  as brpv_mc_vol_tot_6393276fijonp ,
   sum( brpv_mc_vol_tot_6393282varnp)  as brpv_mc_vol_tot_6393282varnp ,
   sum( brpv_mc_vol_tot_6393283fijonp)  as brpv_mc_vol_tot_6393283fijonp ,
   sum( brpv_mc_vol_tot_6393283varnp)  as brpv_mc_vol_tot_6393283varnp ,
   sum( brpv_monto_invenio)  as brpv_monto_invenio ,
   sum( brpv_monto_geopagos)  as brpv_monto_geopagos ,
   sum( brpv_cost_personal_middle)  as brpv_cost_personal_middle ,
   sum( brpv_trx_vi_cre_nac_np_0_2)  as brpv_trx_vi_cre_nac_np_0_2 ,
   sum( brpv_trx_vi_cre_nac_np_2_5)  as brpv_trx_vi_cre_nac_np_2_5 ,
   sum( brpv_trx_vi_cre_nac_np_5_15)  as brpv_trx_vi_cre_nac_np_5_15 ,
   sum( brpv_trx_vi_cre_nac_np_15_50)  as brpv_trx_vi_cre_nac_np_15_50 ,
   sum( brpv_trx_vi_cre_nac_np_50)  as brpv_trx_vi_cre_nac_np_50 ,
   sum( brpv_trx_vi_deb_nac_np_0_2)  as brpv_trx_vi_deb_nac_np_0_2 ,
   sum( brpv_trx_vi_deb_nac_np_2_5)  as brpv_trx_vi_deb_nac_np_2_5 ,
   sum( brpv_trx_vi_deb_nac_np_5_15)  as brpv_trx_vi_deb_nac_np_5_15 ,
   sum( brpv_trx_vi_deb_nac_np_15_50)  as brpv_trx_vi_deb_nac_np_15_50 ,
   sum( brpv_trx_vi_deb_nac_np_50)  as brpv_trx_vi_deb_nac_np_50 ,
   sum( brpv_costo_portafolio_comercio)  as brpv_costo_portafolio_comercio ,
   sum( brpv_costo_portafolio_cuc)  as brpv_costo_portafolio_cuc ,
   sum( brpv_costo_var_trxs_money_send)  as brpv_costo_var_trxs_money_send ,
   sum( brpv_digitacion_monitoreo)  as brpv_digitacion_monitoreo ,
   sum( brpv_dcc_cuotas)  as brpv_dcc_cuotas ,
   sum( brpv_dcc_fee)  as brpv_dcc_fee ,
   sum( brpv_dcc_risk)  as brpv_dcc_risk ,
   sum( brpv_costo_portafolio_codigocomercio_pdv)  as brpv_costo_portafolio_codigocomercio_pdv ,
   sum( brpv_costo_portafolio_codigocomercio_ret)  as brpv_costo_portafolio_codigocomercio_ret ,
   sum( brpv_costo_portafolio_codigocomercio_pro)  as brpv_costo_portafolio_codigocomercio_pro ,
   sum( brpv_costo_portafolio_codigocomercio_gro)  as brpv_costo_portafolio_codigocomercio_gro ,
   sum( brpv_costo_portafolio_codigocomercio_hot)  as brpv_costo_portafolio_codigocomercio_hot ,
   sum( brpv_costo_portafolio_codigocomercio_ps)  as brpv_costo_portafolio_codigocomercio_ps ,
   sum( brpv_costo_portafolio_codigocomercio_taw)  as brpv_costo_portafolio_codigocomercio_taw ,
   sum( brpv_costo_portafolio_cuc_pdv)  as brpv_costo_portafolio_cuc_pdv ,
   sum( brpv_costo_portafolio_cuc_ret)  as brpv_costo_portafolio_cuc_ret ,
   sum( brpv_costo_portafolio_cuc_pro)  as brpv_costo_portafolio_cuc_pro ,
   sum( brpv_costo_portafolio_cuc_gro)  as brpv_costo_portafolio_cuc_gro ,
   sum( brpv_costo_portafolio_cuc_hot)  as brpv_costo_portafolio_cuc_hot ,
   sum( brpv_costo_portafolio_cuc_ps)  as brpv_costo_portafolio_cuc_ps ,
   sum( brpv_costo_portafolio_cuc_taw)  as brpv_costo_portafolio_cuc_taw ,
   sum( brpv_desarrollo_ope)  as brpv_desarrollo_ope ,
   sum( brpv_desarrollo_soporte)  as brpv_desarrollo_soporte ,
   sum( brpv_desarrollo_tec)  as brpv_desarrollo_tec ,
   sum( brpv_desarrollo_sscc)  as brpv_desarrollo_sscc ,
   sum( brpv_gasto_callcenter_pool)  as brpv_gasto_callcenter_pool ,
   sum( brpv_telecarga_licencia_tms_monto)  as brpv_telecarga_licencia_tms_monto ,
   sum( brpv_telecarga_estatemanager_monto)  as brpv_telecarga_estatemanager_monto ,
   sum( brpv_telecarga_ontetime_monto)  as brpv_telecarga_ontetime_monto ,
   sum( brpv_depreciacion_activa)  as brpv_depreciacion_activa ,
   sum( brpv_depreciacion_inactiva)  as brpv_depreciacion_inactiva ,
   sum( brpv_depreciacion_provision)  as brpv_depreciacion_provision ,
   sum( brpv_devoluciones_averias)  as brpv_devoluciones_averias ,
   0 brpv_gasto_correspondencia,--sum( brpv_gasto_correspondencia)  as brpv_gasto_correspondencia ,
   sum( brpv_mrdp_laboratorio)  as brpv_mrdp_laboratorio ,
   sum( brpv_mrdp_llamadas)  as brpv_mrdp_llamadas ,
   sum( brpv_mrdp_atenciones)  as brpv_mrdp_atenciones ,
   sum( brpv_mrdp_parque)  as brpv_mrdp_parque ,
   sum( brpv_trx_sas_pos)  as brpv_trx_sas_pos ,
   sum( brpv_trx_sas_pre)  as brpv_trx_sas_pre ,
   sum( brpv_publicidad_costo_mkt)  as brpv_publicidad_costo_mkt ,
   sum( brpv_publicidad_costo_portafolio)  as brpv_publicidad_costo_portafolio ,
   sum( brpv_ingreso_aportevisa_portafolio)  as brpv_ingreso_aportevisa_portafolio ,
   sum( brpv_gasto_sas_pre)  as brpv_gasto_sas_pre ,
   sum( brpv_gasto_sas_pos)  as brpv_gasto_sas_pos ,
   sum( brpv_gasto_sas_pre_pos)  as brpv_gasto_sas_pre_pos ,
   sum( brpv_gasto_eventual_remplazo_seg)  as brpv_gasto_eventual_remplazo_seg ,
   sum( brpv_gasto_alquiler_almacen)  as brpv_gasto_alquiler_almacen ,
   sum( brpv_ingreso_averia_contometro)  as brpv_ingreso_averia_contometro ,
   sum( brpv_gasto_cyber_source)  as brpv_gasto_cyber_source ,
   sum( brpv_cost_call_afil)  as brpv_cost_call_afil ,
   sum( brpv_gasto_portafolio_segmento)  as brpv_gasto_portafolio_segmento ,
   sum( brpv_ingreso_vendemas_rys)  as brpv_ingreso_vendemas_rys ,
   sum( brpv_costo_vendemas_rys)  as brpv_costo_vendemas_rys ,
   sum( brpv_ingreso_niubiz_rys)  as brpv_ingreso_niubiz_rys ,
   sum( brpv_costo_niubiz_rys)  as brpv_costo_niubiz_rys ,
   sum( brpv_gasto_afiliacion_real)  as brpv_gasto_afiliacion_real ,
   sum( brpv_gasto_afiliacion_provision)  as brpv_gasto_afiliacion_provision ,
   sum( brpv_gasto_afiliacion_extorno)  as brpv_gasto_afiliacion_extorno ,
   sum( brpv_gasto_cuotas_fee_anual_vi)  as brpv_gasto_cuotas_fee_anual_vi ,
   sum( brpv_gasto_cuotas_pipf_vi)  as brpv_gasto_cuotas_pipf_vi ,
   sum( brpv_gasto_cuotas_multas_vi)  as brpv_gasto_cuotas_multas_vi ,
   sum( brpv_gasto_cuotas_suscripciones_vi)  as brpv_gasto_cuotas_suscripciones_vi ,
   sum( brpv_gasto_reintentos_vi)  as brpv_gasto_reintentos_vi ,
   sum( brpv_gasto_cuotas_fee_anual_mc)  as brpv_gasto_cuotas_fee_anual_mc ,
   sum( brpv_gasto_cuotas_pipf_mc)  as brpv_gasto_cuotas_pipf_mc ,
   sum( brpv_gasto_cuotas_multas_mc)  as brpv_gasto_cuotas_multas_mc ,
   sum( brpv_gasto_cuotas_suscripciones_mc)  as brpv_gasto_cuotas_suscripciones_mc ,
   sum( brpv_gasto_reintentos_mc)  as brpv_gasto_reintentos_mc ,
   sum( brpv_gasto_cobro_pagos)  as brpv_gasto_cobro_pagos ,
   sum( brpv_vi_trx_nac_6393244varnp) as brpv_vi_trx_nac_6393244var
from Rentabilidad.aws_silver_post_base_rentabilidad_puntoventa
where brpv_periodo = '202608' AND brpv_fuente ='Niubiz' --AND brpv_codigo_comercio = 651058060 AND brpv_terminal ='93189347'
group by brpv_periodo  ,
   brpv_fuente 
   --brpv_codigo_comercio,
   --brpv_terminal

